//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PrinterUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PRINTERUI_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAMEsav                128
#define IDR_PRINTETYPE                  129
#define IDD_EDITPRINTER                 130
#define IDD_EditAdapterDlg              133
#define IDR_PRINTER_RC                  133
#define IDD_LOGFILE                     134
#define IDR_ADAPTER_RC                  134
#define IDD_REDIRECTDIALOG              136
#define IDD_ADDNTPRINTER                137
#define IDD_INSTALLFROMDISK             140
#define IDB_DOWNARROW                   142
#define IDD_PRINT2FILE                  143
#define IDB_ADAPTER                     144
#define IDB_GROUP                       145
#define IDB_PRINTER                     146
#define IDD_SELECTSHARE                 147
#define IDB_BITMAP1                     148
#define IDB_NETPRINTER                  149
#define IDR_REFRESH                     151
#define IDB_PORT                        156
#define IDR_PRINTER                     157
#define IDB_SHARETREECTRL               169
#define IDR_HELP                        172
#define IDC_IPADDR                      234
#define IDC_EDIT2                       1002
#define IDC_EDIT1                       1003
#define IDC_CLASSIFICATION              1004
#define IDC_EDIT3                       1005
#define PRINTERACCESS                   1005
#define IDC_EDIT4                       1006
#define IDC_EDIT5                       1007
#define IDC_EDIT6                       1008
#define IDC_EDIT7                       1009
#define IDC_EDIT8                       1010
#define IDC_LIST3                       1011
#define IDC_Apply                       1012
#define IDC_ADAPTERPORT                 1012
#define IDC_Quit                        1013
#define IDC_SUSPENDSTATE                1013
#define IDC_REDIRECTPRINTER             1014
#define IDC_NAME                        1015
#define IDC_LOCATION                    1017
#define MAXREQUESTSIZE                  1018
#define IDC_PRINTERCLASS                1019
#define IDC_LIST4                       1020
#define IDC_APPLICATION_LIST            1020
#define IDC_BUTTON1                     1021
#define ID_CLEAR                        1021
#define IDC_BROWSE                      1021
#define IDC_NEWINSTALL                  1021
#define IDC_REFRESH                     1021
#define IDC_BUTTON2                     1022
#define IDC_REDIRECT                    1022
#define IDC_SELECTDRIVER                1022
#define IDC_BUTTON3                     1023
#define IDC_CLEAR                       1023
#define IDC_BUTTON4                     1024
#define IDC_PrinterList                 1029
#define IDC_AdapterList                 1030
#define IDC_PrinterAdapterList          1031
#define IDC_MachineAddress              1037
#define IDC_TypeCombo                   1038
#define IDC_PrinterAccess               1041
#define IDC_LIST2                       1042
#define IDC_LIST1                       1043
#define IDC_DRIVES                      1047
#define IDC_NTDRIVER                    1051
#define IDC_NTBUTTON                    1053
#define IDC_CURRENTINF                  1054
#define IDC_EDIT9                       1055
#define IDC_APPEND                      1056
#define IDC_OVERWRITE                   1057
#define IDC_FILENAME                    1058
#define IDC_FILENAMETEXT                1059
#define IDC_HOSTNAME_ADAPTER_EDIT       1062
#define IDC_LOCATION_ADAPTER_EDIT       1063
#define IDC_APPLICATIONCTRL             1064
#define IDC_SHARES                      1066
#define IDC_TREECTRL                    1067
#define IDC_PRINTERLB                   1068
#define ID_PRINT_ADD                    32771
#define ID_PRINT_EDIT                   32772
#define ID_PRINT_DELETE                 32773
#define ID_ADAPTER_ADD                  32774
#define ID_ADAPTER_EDIT                 32775
#define ID_ADAPTER_DELETE               32776
#define ID_STATUS_HALTPRINTER           32777
#define ID_STATUS_ENABLEPRINTER         32778
#define ID_STATUS_DISABLEQUEUEING       32779
#define ID_STATUS_ENABLEQUEUEING        32780
#define ID_DESKTOPTOPICS                32781
#define ID_GETTINGHELP                  32782
#define ID_WINDOWHELP                   32783
#define ID_FIELDHELP                    32784
#define ID_USERSGUIDE                   32785
#define ID_IDD                          32786
#define ID_SYSADM                       32787
#define ID_TECHSUPPORT                  32788
#define ID_VERSION                      32789
#define ID_REFRESH                      32794
#define ID_REFRSH                       32795
#define ID_USERS_GUIDE                  32817
#define ID_WINDOW_HELP                  32818
#define ID_FIELD_HELP                   32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
