/*
	Copyright(c)2002 Northrop Grumman Corporation

		All Rights Reserved

	This material may be reproduced by or for the U.S. Government pursuant to 
	the copyright license under the clause at Defense Federal Acquisition 
	Regulation Supplement (DFARS) 252.227-7013 (NOV 1995).
*/

#define HT_HelpContents1 1
#define HT_Access 265
#define HT_AccessRoleList 28
#define HT_AccessRoles 29
#define HT_ActiveProcessLimit_ProgramGroup 30
#define HT_ActiveProcessLimit_ServerList 31
#define HT_AdapterIP 32
#define HT_AdapterIPAddress 33
#define HT_AdapterPort 34
#define HT_AdapterType 35
#define HT_Address 266
#define HT_App_Env_File 267
#define HT_Application_s_ 255
#define HT_ApplicationList 38
#define HT_App_Stat 39
#define HT_ArchiveName 40
#define HT_Arguments 41
#define HT_BackupDays 42
#define HT_BackupFileList 43
#define HT_BackupJobList 44
#define HT_BackupTime 45
#define HT_BatchPrinter 256
#define HT_BatchUser 268
#define HT_BootJob 47
#define HT_Classification_Printer 48
#define HT_Classification_Program 49
#define HT_Classification_User 50
#define HT_ClientAddress 51
#define HT_ClientLocation 52
#define HT_ClientSWDIR 53
#define HT_Command 54
#define HT_CommandLine 55
#define HT_CommandLineArgs 56
#define HT_Comment 57
#define HT_ControlRecordList 58
#define HT_ControlRecords 59
#define HT_Copies 60
#define HT_CopyManufacturer_sfilesfrom 61
#define HT_Count_LoginHistory 62
#define HT_Count_SystemLog 63
#define HT_CurrentINF 64
#define HT_CurrentStatus_User 65
#define HT_CurrentStatus_ProgramGroup 66
#define HT_CurrentUserCount 67
#define HT_CustomArguments 68
#define HT_Database 69
#define HT_DatabaseUpdateTime 70
#define HT_DatabaseVersionNumber 71
#define HT_DataFileList 72
#define HT_DataFileRecords 73
#define HT_Date 74
#define HT_DateCreated 75
#define HT_Days 76
#define HT_DefaultPrinter 77
#define HT_Description_EntityFilter 78
#define HT_Description_OutputType 79
#define HT_Description_BatchJob 80
#define HT_Desktop 81
#define HT_Device 82
#define HT_DeviceList 83
#define HT_E_MailAddress 84
#define HT_Enabled 85
#define HT_EndTime 86
#define HT_EnternewMessageBoardname 257
#define HT_Entity 87
#define HT_EntityList 88
#define HT_Entry_ 89
#define HT_Event_LoginHistory 90
#define HT_Event_SystemLog 91
#define HT_EventTime 92
#define HT_Executable_File_ 269
#define HT_Filename_PrintQueue 94
#define HT_Filename_ServerDevice 95
#define HT_FirstName 96
#define HT_Frequency 258
#define HT_FullName 97
#define HT_GroupID 98
#define HT_GroupMembershipList 99
#define HT_HomeDirectory 100
#define HT_Host_Printer 101
#define HT_Host_ProgramGroups 102
#define HT_Host_SystemLog 103
#define HT_Hostname_Adapter 104
#define HT_Hostname_ProcessLimit 105
#define HT_Hostname_ProgramGroup 106
#define HT_Hostname_ServerList 107
#define HT_Hostname_User 108
#define HT_HostName_Hosts 109
#define HT_HostSelection 110
#define HT_IconFile 270
#define HT_IconIndex 271
#define HT_IPAddress 113
#define HT_Items_DefaultPrinter 114
#define HT_Items_NewDevice 115
#define HT_JobClass 116
#define HT_JobName 117
#define HT_JobTitle 118
#define HT_JobType 272
#define HT_LastName 120
#define HT_LastRefreshTime 121
#define HT_Local 122
#define HT_Location_Adapter 123
#define HT_Location_Printer 124
#define HT_LoginEntry 125
#define HT_LoginName 126
#define HT_LoginStatus 127
#define HT_LoginTime 128
#define HT_MachineAddress 129
#define HT_Manufacturers 130
#define HT_MaxRequestSize 131
#define HT_MaximumEntries 132
#define HT_Maximumnumberofentries 133
#define HT_Message 134
#define HT_MessageText 135
#define HT_MessageTitle 136
#define HT_MessageType 137
#define HT_MiddleName 138
#define HT_Name_Backup 139
#define HT_Name_Directories 140
#define HT_Name_Files 141
#define HT_Name_Group 142
#define HT_Name_OutputType 143
#define HT_Name_Printer 144
#define HT_Name_User 145
#define HT_NetworkPrinterList 146
#define HT_NewName 147
#define HT_NewPassword 148
#define HT_NewProcessLimit 149
#define HT_Note 150
#define HT_NTDriver 151
#define HT_NTCSS 152
#define HT_NTCSSDefault 153
#define HT_NTCSSHostName 154
#define HT_NTCSSMasterServer 273
#define HT_NTCSSRole 155
#define HT_NTCSSServer 156
#define HT_OldName 157
#define HT_OldPassword 158
#define HT_Orig_Host 159
#define HT_Owner_Directories 160
#define HT_Owner_Files 161
#define HT_Password 162
#define HT_PasswordLastChanged 163
#define HT_PasswordStatus_AddUser 164
#define HT_PasswordStatus_EditUser 165
#define HT_PasswordStatus_UNIX 166
#define HT_PasswordStatus_User 167
#define HT_PhoneNumber 168
#define HT_PID 169
#define HT_Postto 170
#define HT_PostingDate 171
#define HT_PredefinedJobs 172
#define HT_PrinterAccess 173
#define HT_PrinterAdapterList 174
#define HT_PrinterClass 175
#define HT_PrinterRequestQueue 176
#define HT_PrinterStatus 177
#define HT_Printers_NTPrinter 178
#define HT_Printers_PrintQueue 179
#define HT_Priority 180
#define HT_PrioritySelections 259
#define HT_ProcessLimit_Hosts 181
#define HT_ProcessLimits_ProgramGroups 260
#define HT_ProcessStatusProgram 274
#define HT_ProcessTitles 184
#define HT_Program 275
#define HT_ProgramAccess 185
#define HT_ProgramFile 186
#define HT_ProgramGroup 187
#define HT_ProgramGroupList 188
#define HT_ProgramList 189
#define HT_ProgramTitle 190
#define HT_ProgramType 191
#define HT_Queue_ing_Status 192
#define HT_ReceivedFrom 193
#define HT_RedirectPrinter 194
#define HT_Redirected 195
#define HT_ReleaseDate 196
#define HT_RequestNo_ 197
#define HT_Req_Time 198
#define HT_RestoreFileList 199
#define HT_ScheduleEntries 201
#define HT_Security_Class_ 276
#define HT_SelectedProgramGroup 203
#define HT_Selection_DefaultPrinter 204
#define HT_Selection_Files 205
#define HT_Selection_NewDevice 206
#define HT_Server 277
#define HT_ServerBlockSize 207
#define HT_ServerLocation 208
#define HT_ServerName 209
#define HT_ServerProcessQueue 210
#define HT_ServerSWDIR 211
#define HT_Shell 212
#define HT_Size 213
#define HT_SSNumber 214
#define HT_StartTime 215
#define HT_Status_ApprovedJobs 216
#define HT_Status_CompletedJobs 261
#define HT_Status_PrintQueue 217
#define HT_Status_PrintRequest 218
#define HT_Status_Printer 219
#define HT_Status_ProgramGroups 220
#define HT_Status_ScheduledJobs 221
#define HT_Status_SuspendedJobs 222
#define HT_Subscribeto 223
#define HT_SuspendState 224
#define HT_SystemLogFileName 225
#define HT_Sys_Stat 226
#define HT_TapeDeviceList 227
#define HT_TapeSpecificationList 228
#define HT_TerminationSignal 278
#define HT_Time_BackupJob 262
#define HT_Time_Schedule 263
#define HT_TimeCreated 230
#define HT_Title_Message 231
#define HT_Title_PredefinedJob 232
#define HT_Title_Program 233
#define HT_Title_ProgramGroups 234
#define HT_Type_Adapter 235
#define HT_Type_PredefinedJob 236
#define HT_Type_Printer 237
#define HT_TypeofJob 279
#define HT_UNIXGroup 238
#define HT_UNIXID 239
#define HT_UNIXStatus_AddUser 240
#define HT_UNIXStatus_EditUser 241
#define HT_User_BatchJob 243
#define HT_User_PrintJob 242
#define HT_User_PrintQueue 264
#define HT_UserID 244
#define HT_UserList 245
#define HT_UserMembershipList 246
#define HT_UserName 247
#define HT_UserRole 248
#define HT_VerifyNewPassword 249
#define HT_Version 280
#define HT_VersionNumber 250
#define HT_WorkingDir_ectory_ 281
