/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntcsss_libs_PrintLib */

#ifndef _Included_ntcsss_libs_PrintLib
#define _Included_ntcsss_libs_PrintLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntcsss_libs_PrintLib
 * Method:    getSystemPrinterList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ntcsss_libs_PrintLib_getSystemPrinterList
  (JNIEnv *, jclass);

/*
 * Class:     ntcsss_libs_PrintLib
 * Method:    addPrinter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ntcsss_libs_PrintLib_addPrinter
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     ntcsss_libs_PrintLib
 * Method:    add2KPrinter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ntcsss_libs_PrintLib_add2KPrinter
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     ntcsss_libs_PrintLib
 * Method:    deletePrinter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ntcsss_libs_PrintLib_deletePrinter
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
