/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntcsss_util_SystemOps */

#ifndef _Included_ntcsss_util_SystemOps
#define _Included_ntcsss_util_SystemOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntcsss_util_SystemOps
 * Method:    getUpTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ntcsss_util_SystemOps_getUpTime
  (JNIEnv *, jclass);

/*
 * Class:     ntcsss_util_SystemOps
 * Method:    getCurrentSystemUser
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ntcsss_util_SystemOps_getCurrentSystemUser
  (JNIEnv *, jclass);

/*
 * Class:     ntcsss_util_SystemOps
 * Method:    getSystemEnvironmentVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ntcsss_util_SystemOps_getSystemEnvironmentVariable
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
