/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntcsss_tools_NtcssLp */

#ifndef _Included_ntcsss_tools_NtcssLp
#define _Included_ntcsss_tools_NtcssLp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntcsss_tools_NtcssLp
 * Method:    printTextFilesToLocalPrinter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ZZILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ntcsss_tools_NtcssLp_printTextFilesToLocalPrinter
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring, jboolean, jboolean, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
