#!/bin/sh
#
#
#              Copyright(c)2002 Northrop Grumman Corporation
#
#                          All Rights Reserved
#
#
#    This material may be reproduced by or for the U.S. Government pursuant
#    to the copyright license under the clause at Defense Federal Acquisition
#    Regulation Supplement (DFARS) 252.227-7013 (NOV 1995).
#
#

isup()
{
for i in $genprg
do
    genstr=`ps -e | grep $i | egrep -v "ps -e" | egrep -v "grep ${i}"`
    if [ -n "$genstr" ]
        then
            echo "$upmsg"
        else
            echo "$dnmsg"
    fi
done
}

genprg="gen_se"
upmsg="NTCSSII is Up"
dnmsg="NTCSSII is Down"
isup
genprg="http"
upmsg="WEB     is Up"
dnmsg="WEB     is Down"
isup
