#!/bin/sh
#
#
#              Copyright(c)2002 Northrop Grumman Corporation
#
#                          All Rights Reserved
#
#
#    This material may be reproduced by or for the U.S. Government pursuant
#    to the copyright license under the clause at Defense Federal Acquisition
#    Regulation Supplement (DFARS) 252.227-7013 (NOV 1995).
#
#

# In each directory in /h/USERS: DO.. rename .cshrc and .login

curdir=`pwd`

cd /h/USERS

for i in `ls`
do
    if [ -d "${i}" ]
    then
        echo "Directory: ${i}"
        if [ -f "${i}/.cshrc" ]
        then
            mv "${i}"/.cshrc "${i}"/cshrc.null
            echo ".....cshrc renamed"
        fi
        if [ -f "${i}/.login" ]
        then
            mv "${i}"/.login "${i}"/login.null
            echo ".....login renamed"
        fi
        echo " "
    fi
done

cd $curdir
