/*
	Copyright(c)2002 Northrop Grumman Corporation

		All Rights Reserved

	This material may be reproduced by or for the U.S. Government pursuant to 
	the copyright license under the clause at Defense Federal Acquisition 
	Regulation Supplement (DFARS) 252.227-7013 (NOV 1995).
*/

// 0_basics.h                    
//                                         
// This file is a 'includer convenience' and includes header files that
// are needed by all DLL source files.
// 
//----------------------------------------------------------------------

#ifndef _INCLUDE_0_BASICS_H_CLASS_
#define _INCLUDE_0_BASICS_H_CLASS_

#include "ntcssdef.h"
#include "dll_defs.h"
#include "dlluser.h"
#include "DllMan.h"
#include "version.h"
#include "dbg_defs.h"

#endif // _INCLUDE_0_BASICS_H_CLASS_
