#!/bin/sh
#
#
#              Copyright(c)2002 Northrop Grumman Corporation
#
#                          All Rights Reserved
#
#
#    This material may be reproduced by or for the U.S. Government pursuant
#    to the copyright license under the clause at Defense Federal Acquisition
#    Regulation Supplement (DFARS) 252.227-7013 (NOV 1995).
#
#
#######################################################################
#######################################################################

PROFDIR="/h/NTCSSS/applications/data/unix_uga/shell"
NTCSSDATADIR="/h/NTCSSS/database"
DOMAIN_FLAG="DOMAIN"
TELLNT="YES"
TELLPWD="YES"
DEF_NTDIR="c:/h/Users"
PWDIR=/etc/passwd
DEFNTGROUP=NTCSS

disp=`echo ${DISPLAY} | sed -n "s/\([^:]*\).*/\1/p"`
ntdir="d:/h"

# get NT Group info
sys_line=`grep NTGROUP ${NTCSSDATADIR}/SYS_CONF`
if [ -n "${sys_line}" ]
then
        ntgroup=`echo ${sys_line} | sed -n "s/[^:]*.\(.*\)$/\1/p"`
        if [ -z "${ntgroup}" ]
        then
                ntgroup=${DEFNTGROUP}
        fi
else
        ntgroup=${DEFNTGROUP}
fi


check_user=`grep "^${1}:" $PWDIR 2> /dev/null`
if [ -n "$check_user" ]
then
        sys_line=`grep NTUSERDIR ${NTCSSDATADIR}/SYS_CONF`
        if [ -n "${sys_line}" ]
        then
                ntdir=`echo ${sys_line} | sed -n "s/[^:]*.\(.*\)$/\1/p"`
                if [ -z "${ntdir}" ]
                then
                        ntdir=${DEF_NTDIR}
                fi
        else
                ntdir=${DEF_NTDIR}
        fi

	if [ $# -eq 4 ]
	then 
		DISPLAY=""
		/h/NTCSSS/applications/data/users_conf/user_config CHANGEPASSWD "$1" "$3" "$4"
	    DISPLAY="${disp}:0.0"
	fi

        tmpuser="NONE"
        sys_line=`grep NTTMPUSER ${NTCSSDATADIR}/SYS_CONF`
        if [ -n "${sys_line}" ]
        then
                tmpuser=`echo ${sys_line} | sed -n "s/[^:]*.\(.*\)$/\1/p"`
                if [ -z "${tmpuser}" ]
                then
                        tmpuser="NONE"
                fi
        fi

        ntprof="NONE"
        sys_line=`grep NTPROFDIR ${NTCSSDATADIR}/SYS_CONF`
        if [ -n "${sys_line}" ]
        then
                ntprof=`echo ${sys_line} | sed -n "s/[^:]*.[ ]*\(.*\)$/\1/p"`
                if [ -z "${ntprof}" ]
                then
                        ntprof="NONE"
                fi
        fi


        if [ "${TELLNT}" = "YES" ]
        then
             /h/NTCSSS/bin/adduser "${disp}" /ADDEXT "$1" "$3" "$2" ${ntdir}\\${1} $tmpuser "${ntprof}\\${1}" $DOMAIN_FLAG
	fi

fi
